example:
  property: "I am in production"
server:
  port: 8080

spring:
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://10.10.1.10:5432/iipdb"
    username: "iipwoomi"
    password: "iipwoomi"
    testWhileldle: "true"
    validationQuery: "SELECT 1"
  jpa:
    show-sal: "true"
    database: "POSTGRESQL"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
