example.property: "I am in dev, updated version 1"

server:
  port: 18080

spring:
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: "postgres"
    url: "jdbc:postgresql://10.10.1.10:5432/iipdb"
    username: "iip"
    password: "iip"
    testWhileldle: "true"
    validationQuery: "SELECT 1"
  jpa:
    show-sal: "true"
    database: "POSTGRESQL"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
