server: 
    port: 8888 # 스프링 클라우드 컨피그 서버가 수신 대기하는 포트
spring:
    profiles:
        active: native # 구성 정보를 저장할 백엔드 저장소(파일 시스템)
    cloud:
        config:
            server:
                native:
                    searchLocations: file:///Users/whoana/DEV/workspace-msa/crud-config-server/src/main/resources/config/loginservice
